# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee92a91ee4cd35835ced6935a4285625da23fcdfb9e5fb06dc1567688abe593630070f53241bb2de600328ba66edc6d404c02f90f924c92666f021f5c4beb00f

test:
  secret_key_base: f2d27c0754fbabca3ce4ce44664592a4d8852653b5746f126873a848b8c38487bf1ef07e6764533dc1bb5a34404c3d49c22fd82564c8fc24f4cf3584ee560aea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
